kind: Service
apiVersion: v1
metadata:
  name: ej9-bot
  namespace: bot
  labels:
    app: ej9-bot
spec:
  selector:
    app: ej9-bot
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort

